### ISSUE TITLE
Search some pegs and create UI designs/layout using any photo editors like PS and AI (Forms and Landing Page)

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#12]
This will be the first step in creating our website. It serves as a guide/model for us to be able to do HTML coding in an easy flow. **Please consider the FONTS, LOGOS, COLOR SCHEME and ORGANIZATION** of the layout. It should be appropriate and formal.

**Create the ff designs for:**
- Forms (login, signup, application forms)
- Landing Page

**Comment by ShairaTinchay** [comment]
![Landing Page.png](https://zube.io/files/IT3A-2016/dbc320a3570b0c59b78214c5f8b001be.png)
![Ap form.png](https://zube.io/files/IT3A-2016/8c95b8d55f07982e5fd98872372b4431.png)
