### ISSUE TITLE
Search some pegs and create UI designs/layout using any photo editors like PS and AI (Dashboards)

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#14]

**Comment by mariane21** [comment]
This will be the first step in creating our website. It serves as a guide/model for us to be able to do HTML coding in an easy flow. **Please consider the FONTS, LOGOS, COLOR SCHEME and ORGANIZATION** of the layout. It should be appropriate and formal.

**Create the ff designs for:**
- Student Dashboard
- Admin Dashboard

**Comment by jhanning29** [comment]
Marian Allen! here na ang links ng pwedeng design ng dashboard :)
https://dribbble.com/shots/2080862-Sm-rrebr-d-app/attachments/373979
![2.jpg](https://zube.io/files/IT3A-2016/ffad4d49978da4bfede57b29ad4b38aa.jpeg)

**Comment by jhanning29** [comment]
![1.jpg](https://zube.io/files/IT3A-2016/ca7a115a8a916187af36eb53c992624e.jpeg)
![4.jpg](https://zube.io/files/IT3A-2016/9db1026695484ac7c1b1439a54885672.jpeg)

**Comment by mariane21** [comment]
Thank you. I've already downloaded a free template of this one. It is similar to the layout of out student portal. We just need to modify it.
