### ISSUE TITLE
Search about printing features with same layout format

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#17]
Look for a code in html or jscript that will print a report in an appropriate layout.

**Comment by markangeloamador** [comment]
Links:
Site:
https://css-tricks.com/html-invoice/

View Demo link :
https://css-tricks.com/examples/EditableInvoice/

**Comment by mariane21** [comment]
Thank you angelo, but this is too ambiguous. Search for more.. If you know what I mean haha. Sorry.. well, I appreciate your effort anyway :)
