### ISSUE TITLE
Search and learn about search engines with filters

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#18]
Look for a code or sample features that is using filters for searching specific info. (Java Script ata to)

**Comment by ShairaTinchay** [comment]
Links that I've search:
http://stackoverflow.com/questions/3510233/how-to-make-html-page-a-search-engine
http://www.textfixer.com/tutorials/html-search-box.php
https://developers.google.com/custom-search/docs/api
https://sourceforge.net/directory/os:windows/?q=custom%20php%20search%20engine

I download one compressed file and try to run it. 

![search engine.JPG](https://zube.io/files/IT3A-2016/efe6bb759b5d1f89052ba87f5498b22c.jpeg)

**Comment by mariane21** [comment]
Thank you. These are helpful in understanding the function of search engine. Anyway, there's also a search bar feature in the template that I've downloaded and its working. We just need to modify it and understand its syntax. Mahirap galawin kasi di ko gamay ang jquery. :) Dont worry, I'll assure you magagamit natin to bigtime.
