### ISSUE TITLE
Search for more additional useful features that can be helpful in dashboards. Basically, an idea.

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#19]
Example of this are:

- basic calculations
- sending buttons

**Comment by jhanning29** [comment]
hey allen, are na po yung nahanap kong pwedeng features ng dashboard natin, dunno if this will help.
http://www.datapine.com/blog/top-15-dashboard-features/
https://wrapbootstrap.com/theme/nifty-responsive-admin-template-WB0048JF7
https://support.google.com/analytics/answer/1068218?hl=en
https://wrapbootstrap.com/theme/kingadmin-responsive-admin-dashboard-WB09JXK43
https://colorlib.com/wp/free-html5-admin-dashboard-templates/

**Comment by mariane21** [comment]
Thank you but I dont think that we need calculations for this project, but let's see :) You can explore for some/more ideas to be added.
