### ISSUE TITLE
Code for application form pt.1

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#2]
Please make sure that the fields to be filled up are existing and valid. Please refer to the gathered information for you to be able to know what fields to inlcude

**Comment by mariane21** [comment]
Please prioritize the important fields first. You have the sample hard copy of the form, please focus on the first and second page.

**Comment by ShairaTinchay** [comment]
![code app.JPG](https://zube.io/files/IT3A-2016/4c540b0e2ea77ed7fb3f1110c5c9d86b.jpeg)
