### ISSUE TITLE
Search on how to convert web based app into a mobile

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#21]

**Comment by mariane21** [comment]
Cite samples and applications on how to convert web based app into mobile app. Watch tutorials.

**Comment by markangeloamador** [comment]
Links: 
http://www.mobappcreator.com/?gclid=COG1r5WI49ECFYZjvAodTp8KpQ

http://ibuildapp.com/how-to-convert-website-to-android-and-ios-mobile-app/

http://www.appypie.com/convert-website-to-mobile-apps

https://smallbiztrends.com/2015/02/places-that-turn-your-website-into-an-app.html

**Comment by mariane21** [comment]
http://phonegap.com/getstarted/ - I think this is better
