### ISSUE TITLE
Search for a notification function/feature to be used in admin's dashboard

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#26]
Look for a java script code. :) Cite some samples also.

**Comment by ShairaTinchay** [comment]
Links that I've search:
https://pusher.com/tutorials/realtime-notifications
https://pear.php.net/package/Event_Dispatcher/docs/latest/__filesource/fsource_Event_Dispatcher__Event_Dispatcher-1.1.0EventNotification.php.html
http://stackoverflow.com/questions/2271156/chrome-desktop-notification-example
https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

**Comment by mariane21** [comment]
Thank you. I've already check these -- these are not that familiar pero sama sama tayong tuklasin ang mundong ito
