### ISSUE TITLE
Code Landing Page

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#3]
Please make it a single page with an appropriate layout basing on the design made.

**Comment by jhanning29** [comment]
ellen here's the code for the landing page, please check if may dapat bang idag-dag :)
![code2.png](https://zube.io/files/IT3A-2016/bdc34335e5fefde2b333e32c3980f5d3.png)
![code1.png](https://zube.io/files/IT3A-2016/8aa1bfe3821bb5ce6be0f7774b5f219e.png)
![code4.png](https://zube.io/files/IT3A-2016/7b483d0b6e422a9afd77ec9efaa45315.png)
![code5.png](https://zube.io/files/IT3A-2016/f0760f62667980af258e88524628d828.png)
![code3.png](https://zube.io/files/IT3A-2016/4c42c57d7dde83df314674f0f0bb896a.png)
![code6.png](https://zube.io/files/IT3A-2016/90c5b3413517d13562fadb835bdc444c.png)

wait! bakit ganito? wala talaga nalabas na picture?

**Comment by jhanning29** [comment]
ay meron pala sorna :)
