### ISSUE TITLE
Information Architecture for student dashboard

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#40]
You can search again different layouts and combine it as one. If you think such functions are necessary to the system, please include it.

Basta di mawawala yung nasa design nung simula..

**Comment by mariane21** [comment]
@ShairaTinchay  pakibigay po kay ate jhana yung kinode mo sa application form, kasama din yon :)

**Comment by mariane21** [comment]
As part of your task, just make a simple architecture for student dashboard. Not that focusing on the design but focus on the content. It must be functional as a UI so that we can easily modify it when we attach some others onto it

**Comment by mariane21** [comment]
Also please upload your work sa group or drive natin. Thank you

**Comment by jhanning29** [comment]
are na at last! di pa final yung colorscheme ko dito ha! medyo jeje pa. ayusin na lang pag meron na din idadagdag yung kabilang group. di ko pa din alam yung code para pakapagpalit ng profile pic yung student :(

**Comment by jhanning29** [comment]
![dash.png](https://zube.io/files/IT3A-2016/83c8d08514e316799028843a9d025816.png)
