### ISSUE TITLE
Connect the code made in sprint 2 (Application Form) pt1

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#48]

**Comment by mariane21** [comment]
Since sobrang dami nito at may mga validations pa, I'll part into two :) I'll give you the code that I made in sprint2 for you to be able to make this task. Try and error ka lang beks. Bale kunin mo na lang din saki ang database for student application :)

PS. Wala pang validations yung mga gawa ko. Pure insertion lang yon. No CRUDs yet.

**Comment by ShairaTinchay** [comment]
Still, figuring out. I have a right syntax of code at ganun din sabi ng iba pero ayaw gumana.  There's no error, but there's no data na binabato sa database. Anyways I'll send you kung ano nagawa ko.
