### ISSUE TITLE
Coordinate about the dashboard's UI and UX made by XENO (Student)

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#50]
Please see its information architecture and apply the information architecture you made in student dashboard.

**Comment by jhanning29** [comment]
halos same lang din ang eto sa dashboard ng admin beks! ikaw na lang bahala sa color ha at super jejemon din ang color nyancan't get in touch sa group lead ng kabila
si casey naman di pa tapos gawin pala yung dashboard nila so again im using our own design

**Comment by jhanning29** [comment]
nasa zipped file lahat ng code na pinasa ko beks :)

**Comment by jhanning29** [comment]
![dashy1.png](https://zube.io/files/IT3A-2016/024fcaccc834b5d22bda323d611aed36.png)
