### ISSUE TITLE
Coordinate about the dashboard's UI and UX made by XENO (SLSS)

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#51]
This is also like your other task. please include the functions that we need for this one. You better refer to Jasper for this concern.

**Comment by jhanning29** [comment]
allen, nakuha ko na yung dashboard ng kabilang group. i'll update you kung ano na later :)

**Comment by jhanning29** [comment]
waah! i forgot to attach the zipped file na pinasa ng XENO sakin :( nasa net shop ako para magupdate at walang net :(

**Comment by jhanning29** [comment]
are na lang muna still not decided kung anong or kaninong dashboard gagamitin eh so yung atin nalang muna isesend ko magulo pa yung kanila eh

**Comment by jhanning29** [comment]
![sys1.png](https://zube.io/files/IT3A-2016/e2043e9e03acd7ab24097b5a48c6c3ae.png)
![sys2.png](https://zube.io/files/IT3A-2016/f74a9d7be88b5c7f2d5b04baa3a5e1f1.png)

**Comment by jhanning29** [comment]
send ko na din sayo yung zipped file for the codes neto allen
