### ISSUE TITLE
Get the list of personnel to ma'am jane

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#52]
Since you've done this already in our sprint 2, I'll still include this in this sprint.
Please wait Ms.Jane approval and more info, for she's in Davao right now.
Sanay ka namang maghintay hahaha basta daan daanan mo lang sya lagi sa office nya :)

**Comment by markangeloamador** [comment]
Hahah. Okay na M.A nakuha ko na nung wed pa. Binigay ko na rin sayo kahapon.
 Haha Sige Salamat :)

**Comment by markangeloamador** [comment]
M.A eto yun. Hahahehe :) 

![Names Personnel.jpg](https://zube.io/files/IT3A-2016/67ec00a6a9e5222a8aa3a26868117433.jpeg)

**Comment by mariane21** [comment]
Ok na. Convinced na ko hahaha. Salamat :)
