### ISSUE TITLE
SLSS personnel database

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#53]
create tables and fields for the master file of admins - eto yung mga personnel sa slss (Yung mga nakuha mo). I need it asap.

**Comment by mariane21** [comment]
![g.PNG](https://zube.io/files/IT3A-2016/36421d247e96e3de78a2d8c214e3478d.png)

@markangeloamador since you have the original hard copy of this one, please follow this format para tugma sa tables na nasa pauna nating database, okay? Salamat

**Comment by mariane21** [comment]
need it po ASAP - kelangan ko po yan sa dashboard at login.

**Comment by markangeloamador** [comment]
Ahh.. Tapos ko na M.A
Okay na Salamat :)

![Names Personnel code.PNG](https://zube.io/files/IT3A-2016/d2fece04f1b3684a059352d5fa37d829.png)

**Comment by mariane21** [comment]
Thank you :)
