### ISSUE TITLE
Systematize the final database of students and admin to be used

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#57]
If sa akin ang interfaces sayo naman ang database. Medyo madali to compare to mine because we already made our database. The problem is magkaiba tayo ng database ng XENO. We should have the same database kasi magkakagulo tayo sa data lalo na sa variables na gagamitin. I need this ASAP ha. Coordinate with XENO ha.

**Comment by mariane21** [comment]
@markangeloamador sabi ko nga much better kung yung atin ang gagamitin kasi sa SLSS talaga galing and mdeyo makatotohanan naman kahit mock data lang sa stud.. bigyan mo ng copy ng finalized database natin ang XENO. Okay ha? tHANK You

**Comment by mariane21** [comment]
*Thank You HAHAHA jejemon tuloy

**Comment by mariane21** [comment]
I need this before friday. If may klase ka or hadlang sa sched mo, address me asap

**Comment by markangeloamador** [comment]
-Good Evening M.A.
Nabago ko na yung mga pinabago nyo. Pa check na lang po. :)

**Comment by mariane21** [comment]
Okay. Salamat :) Ako na magsasabi sa XENO :)
