### ISSUE TITLE
Search codes for CRUD functions to be used in application form

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#59]
I'm familiar with this one so I can help you with this. If masyado broad for you, you can learn from the works of the other group, tuturuan ka rin nila :) Then share mo sa amin yung natutunan mo para mapagsama sama natin brain cells natin joke, kaalaman natin dito. Dont worry katulong din natin ang XENO dito, inaasign lang kita for this because ikaw ang assign sa buong application form (ui and database) at para di rin ako mag-isa kasi sawang sawa na kong mag-isa :(

**Comment by ShairaTinchay** [comment]
This is it. I've search some sample and here some screenshot. Thank you to Dennis and his groupmate who help me.

![Code CRUD.png](https://zube.io/files/IT3A-2016/abccdafcee86454418ffa60f24e77224.png)
![CRUD PS.png](https://zube.io/files/IT3A-2016/7a3e0797079e121ac07cf1e1cf69d4c5.png)
